; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.4 on Sat Jul 20 2024 14:48:56 GMT+0200 (czas środkowoeuropejski letni)

M116 P0 ; wait for tool temperatures to be reached
